apiVersion : apps/v1
kind: Deployment
metadata:
  name: apiacoes 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apiacoes
  template:
    metadata:
      labels:
        app: apiacoes
    spec:
      containers:
        - name: apiacoes
          image: renatogroffe/apiacoes-monitoramento:1.0
          env:
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: secrets-apiacoes
                  key: ChaveApplicationInsights
            - name: ConnectionStrings__AppConfiguration
              valueFrom:
                secretKeyRef:
                  name: secrets-apiacoes
                  key: ConexaoAppConfiguration
          ports:
            - containerPort: 80